"""schema initial EDR multi-utilisateurs

Revision ID: 73b95d55de3a
Revises: 
Create Date: 2026-08-11 22:53:37.860647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '73b95d55de3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('os_name', sa.String(length=120), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_isolated', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('events_received', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('hash_algo', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=2), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('N1','N2','N3')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('machine_pk', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=255), nullable=True),
    sa.Column('parent_name', sa.String(length=255), nullable=True),
    sa.Column('parent_pid', sa.Integer(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('new','acknowledged','in_progress','closed','false_positive')", name='ck_alerts_status'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_pk'], ['machines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_detected_at'), 'alerts', ['detected_at'], unique=False)
    op.create_index('ix_alerts_detected_desc', 'alerts', [sa.text('detected_at DESC')], unique=False)
    op.create_index(op.f('ix_alerts_machine_pk'), 'alerts', ['machine_pk'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_detected', 'alerts', ['status', sa.text('detected_at DESC')], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_source', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_occurred_desc', 'audit_logs', [sa.text('occurred_at DESC')], unique=False)
    op.create_table('exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('Folder','Process','Extension')", name='ck_exclusions_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'path', name='uq_exclusions_type_path')
    )
    op.create_table('metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('machine_pk', sa.Integer(), nullable=True),
    sa.Column('bucket_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('files_created', sa.Integer(), nullable=False),
    sa.Column('files_deleted', sa.Integer(), nullable=False),
    sa.Column('files_renamed', sa.Integer(), nullable=False),
    sa.Column('unique_extensions', sa.Integer(), nullable=False),
    sa.Column('entropy_filenames', sa.Float(), nullable=False),
    sa.Column('processes_created', sa.Integer(), nullable=False),
    sa.Column('child_processes', sa.Integer(), nullable=False),
    sa.Column('process_depth', sa.Integer(), nullable=False),
    sa.Column('connections', sa.Integer(), nullable=False),
    sa.Column('unique_ips', sa.Integer(), nullable=False),
    sa.Column('external_connections', sa.Integer(), nullable=False),
    sa.Column('dns_queries', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_alert', sa.Boolean(), nullable=False),
    sa.Column('baseline_trained', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_pk'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_bucket_at'), 'metrics', ['bucket_at'], unique=False)
    op.create_index('ix_metrics_machine_bucket', 'metrics', ['machine_pk', sa.text('bucket_at DESC')], unique=False)
    op.create_index(op.f('ix_metrics_machine_pk'), 'metrics', ['machine_pk'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_source', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('machine_pk', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_pid', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("action IN ('KILL','ISOLATE','UNISOLATE')", name='ck_commands_action'),
    sa.CheckConstraint("status IN ('pending','sent','acked','failed','expired')", name='ck_commands_status'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['machine_pk'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_created_at'), 'commands', ['created_at'], unique=False)
    op.create_index('ix_commands_dispatch', 'commands', ['machine_pk', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_commands_machine_pk'), 'commands', ['machine_pk'], unique=False)
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index(op.f('ix_commands_machine_pk'), table_name='commands')
    op.drop_index('ix_commands_dispatch', table_name='commands')
    op.drop_index(op.f('ix_commands_created_at'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_metrics_machine_pk'), table_name='metrics')
    op.drop_index('ix_metrics_machine_bucket', table_name='metrics')
    op.drop_index(op.f('ix_metrics_bucket_at'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_table('exclusions')
    op.drop_index('ix_audit_occurred_desc', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    op.drop_index('ix_alerts_status_detected', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_machine_pk'), table_name='alerts')
    op.drop_index('ix_alerts_detected_desc', table_name='alerts')
    op.drop_index(op.f('ix_alerts_detected_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
